controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_wheel_joint_position_controller:
      type: position_controllers/JointGroupPositionController

    left_wheel_joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_wheel_joint_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    right_wheel_joint_position_controller:
      type: position_controllers/JointGroupPositionController

    right_wheel_joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_wheel_joint_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    group_position_controller:
      type: position_controllers/JointGroupPositionController

    group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    group_effort_controller:
      type: effort_controllers/JointGroupEffortController

left_wheel_joint_position_controller:
  ros__parameters:
    joints:
      - left_wheel_joint

left_wheel_joint_velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint

left_wheel_joint_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint

right_wheel_joint_position_controller:
  ros__parameters:
    joints:
      - right_wheel_joint

right_wheel_joint_velocity_controller:
  ros__parameters:
    joints:
      - right_wheel_joint

right_wheel_joint_effort_controller:
  ros__parameters:
    joints:
      - right_wheel_joint

group_position_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint

group_velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint

group_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
