<?xml version="1.0"?>
<!-- TODO add name here? -->
<!-- <robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rosbot"> -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="rosbot" params="prefix">

    <!-- constants -->
    <xacro:property name="PI" value="3.1415926535897931"/>

    <!-- body properties -->
    <xacro:property name="body_mass" value="6.0" />
    <xacro:property name="body_width" value="0.46" />
    <xacro:property name="body_length" value="0.3" />
    <xacro:property name="body_height" value="0.17" />
    <xacro:property name="body_ground_offset" value="0.0575" />

    <!-- lidar properties -->
    <!-- <xacro:property name="lidar_width" value="0.055" /> -->
    <!-- <xacro:property name="lidar_length" value="0.055" /> -->
    <xacro:property name="lidar_height" value="0.055" />
    <xacro:property name="lidar_radius" value="0.0275" />

    <!-- rear wheel properties -->
    <xacro:property name="real_wheel_mass" value="0.5" />
    <xacro:property name="rear_wheel_width" value="0.05" />
    <xacro:property name="rear_wheel_radius" value="0.0975" />
    <xacro:property name="rear_wheel_ground_offset" value="0.0975" />
    <xacro:property name="rear_wheel_axis_offset" value="0.1" />
    <xacro:property name="rear_wheel_distance" value="0.241" />

    <!-- robot is 300mm wide, 460mm long, 170mm tall -->
    <!-- front wheels are 38.5mm off the ground surface -->
    <!-- robot body is 57.5mm off the ground surface -->
    <!-- robot rear wheel diameter is 195mm (radius 97.5mm) -->
    <!-- robot rear wheels axis is 97.5mm off the ground surface -->
    <!-- robot rear wheels axis is 100mm from the center of the body -->
    <!-- front wheel radius 77mm  -->
    <!-- robot front wheels axis is -267.57mm from the center of the body -->
    <!-- small motor pulley has 16 teeth -->
    <!-- large wheel pulley has 72 teeth -->
    <!-- motor to wheel gear ratio is 72/16 = 4.5 -->

    <!-- base link -->
    <link name="${prefix}base_link">
      <collision>
        <origin xyz="${rear_wheel_axis_offset} 0 ${body_height/2 + body_ground_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${body_width} ${body_length} ${body_height}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="${rear_wheel_axis_offset} 0 ${body_height/2 + body_ground_offset}" rpy="0 0 0"/>
        <geometry>
          <!-- <box size="${body_width} ${body_length} ${body_height}"/> -->
          <!-- TODO replace simple box with robot mesh -->
          <mesh filename="package://rosbot_description/meshes/rosbot_body.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <!-- <inertial>
        <origin xyz="${rear_wheel_axis_offset} 0 ${body_height/2 + body_ground_offset}" rpy="0 0 0"/>
        <mass value="${body_mass}"/>
        <inertia ixx="${body_mass / 12.0 * (body_length*body_length + body_height*body_height)}" ixy="0.0" ixz="0.0" iyy="${body_mass / 12.0 * (body_height*body_height + body_width*body_width)}" iyz="0.0" izz="${body_mass / 12.0 * (body_width*body_width + body_length*body_length)}"/>
      </inertial> -->
    </link>

    <!-- body -->
    <!-- <joint name="${prefix}body_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}body"/>
      <origin xyz="0 0 ${body_height + body_ground_offset + lidar_height / 2}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${prefix}body">
      <visual>
        <origin xyz="0 0 ${body_height + body_ground_offset + lidar_height / 2}" rpy="0 0 0"/>
        <geometry>
          <box size="${lidar_width} ${lidar_length} ${lidar_height}"/>
        </geometry>
        <material name="green"/>
      </visual>

      <inertial>
        <origin xyz="${rear_wheel_axis_offset} 0 ${body_height/2 + body_ground_offset}" rpy="0 0 0"/>
        <mass value="${body_mass}"/>
        <inertia ixx="${body_mass / 12.0 * (body_length*body_length + body_height*body_height)}" ixy="0.0" ixz="0.0" iyy="${body_mass / 12.0 * (body_height*body_height + body_width*body_width)}" iyz="0.0" izz="${body_mass / 12.0 * (body_width*body_width + body_length*body_length)}"/>
      </inertial>
    </link> -->

    <!-- left wheel -->
    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="0 -${rear_wheel_distance/2} ${rear_wheel_ground_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>
    <link name="${prefix}left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${rear_wheel_width}" radius="${rear_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${rear_wheel_width}" radius="${rear_wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${real_wheel_mass}"/>
        <inertia ixx="${real_wheel_mass / 12.0 * (3*rear_wheel_radius + rear_wheel_width*rear_wheel_width)}" ixy="0.0" ixz="0.0" iyy="${real_wheel_mass / 12.0 * rear_wheel_radius*rear_wheel_radius}" iyz="0.0" izz="${real_wheel_mass / 12.0 * rear_wheel_radius*rear_wheel_radius}"/>
      </inertial>
    </link>

    <!-- right wheel -->
    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="0 ${rear_wheel_distance/2} ${rear_wheel_ground_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>
    <link name="${prefix}right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${rear_wheel_width}" radius="${rear_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${rear_wheel_width}" radius="${rear_wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${real_wheel_mass}"/>
        <inertia ixx="${real_wheel_mass / 12.0 * (3*rear_wheel_radius + rear_wheel_width*rear_wheel_width)}" ixy="0.0" ixz="0.0" iyy="${real_wheel_mass / 12.0 * rear_wheel_radius*rear_wheel_radius}" iyz="0.0" izz="${real_wheel_mass / 12.0 * rear_wheel_radius*rear_wheel_radius}"/>
      </inertial>
    </link>

    <!-- lidar -->
    <joint name="${prefix}lidar_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}lidar"/>
      <origin xyz="${rear_wheel_axis_offset} 0 ${body_ground_offset + body_height + lidar_height / 2}" rpy="0 0 ${PI}"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${prefix}lidar">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <!-- <box size="${lidar_width} ${lidar_length} ${lidar_height}"/> -->
          <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
        </geometry>
        <material name="green"/>
      </visual>
    </link>

  </xacro:macro>

</robot>
