<?xml version="1.0"?>
<!-- TODO add name here? -->
<!-- <robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rosbot"> -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="rosbot" params="prefix">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="6.0" />

    <xacro:property name="body_width" value="0.46" />
    <xacro:property name="body_length" value="0.3" />
    <xacro:property name="body_height" value="0.17" />

    <xacro:property name="lidar_width" value="0.055" />
    <xacro:property name="lidar_length" value="0.055" />
    <xacro:property name="lidar_height" value="0.055" />

    <xacro:property name="wheel_mass" value="0.5" />
    <!-- arbitrary value for wheel mass -->
    <xacro:property name="wheel_len" value="0.05" />
    <xacro:property name="wheel_radius" value="0.0975" />

    <xacro:property name="frame_ground_offset" value="0.0575" />

    <xacro:property name="rear_wheel_ground_offset" value="0.0975" />
    <xacro:property name="rear_wheels_axis_offset" value="0.1" />
    <xacro:property name="rear_wheels_distance" value="0.241" />
    <!-- Space btw top of beam and the each joint -->

    <!-- robot is 300mm wide, 460mm long, 170mm tall -->
    <!-- front wheels are 38.5mm off the ground surface -->
    <!-- robot body is 57.5mm off the ground surface -->
    <!-- robot rear wheel diameter is 195mm (radius 97.5mm) -->
    <!-- robot rear wheels axis is 97.5mm off the ground surface -->
    <!-- robot rear wheels axis is 100mm from the center of the body -->
    <!-- front wheel radius 77mm  -->
    <!-- robot front wheels axis is -267.57mm from the center of the body -->
    <!-- small motor pulley has 16 teeth -->
    <!-- large wheel pulley has 72 teeth -->
    <!-- motor to wheel gear ratio is 72/16 = 4.5 -->

    <!-- base link -->
    <link name="${prefix}base_link">
      <collision>
        <origin xyz="${rear_wheels_axis_offset} 0 ${body_height/2 + frame_ground_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${body_width} ${body_length} ${body_height}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="${rear_wheels_axis_offset} 0 ${body_height/2 + frame_ground_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${body_width} ${body_length} ${body_height}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <!-- <inertial>
        <origin xyz="${rear_wheels_axis_offset} 0 ${body_height/2 + frame_ground_offset}" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <inertia ixx="${base_mass / 12.0 * (body_length*body_length + body_height*body_height)}" ixy="0.0" ixz="0.0" iyy="${base_mass / 12.0 * (body_height*body_height + body_width*body_width)}" iyz="0.0" izz="${base_mass / 12.0 * (body_width*body_width + body_length*body_length)}"/>
      </inertial> -->
    </link>

    <!-- body -->
    <!-- <joint name="${prefix}body_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}body"/>
      <origin xyz="0 0 ${body_height + frame_ground_offset + lidar_height / 2}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${prefix}body">
      <visual>
        <origin xyz="0 0 ${body_height + frame_ground_offset + lidar_height / 2}" rpy="0 0 0"/>
        <geometry>
          <box size="${lidar_width} ${lidar_length} ${lidar_height}"/>
        </geometry>
        <material name="green"/>
      </visual>

      <inertial>
        <origin xyz="${rear_wheels_axis_offset} 0 ${body_height/2 + frame_ground_offset}" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <inertia ixx="${base_mass / 12.0 * (body_length*body_length + body_height*body_height)}" ixy="0.0" ixz="0.0" iyy="${base_mass / 12.0 * (body_height*body_height + body_width*body_width)}" iyz="0.0" izz="${base_mass / 12.0 * (body_width*body_width + body_length*body_length)}"/>
      </inertial>
    </link> -->

    <!-- left wheel -->
    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="0 -${rear_wheels_distance/2} ${rear_wheel_ground_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>
    <link name="${prefix}left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0" iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0" izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

    <!-- right wheel -->
    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="0 ${rear_wheels_distance/2} ${rear_wheel_ground_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>
    <link name="${prefix}right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0" iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0" izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

    <!-- lidar -->
    <joint name="${prefix}lidar_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}lidar"/>
      <origin xyz="${-rear_wheels_axis_offset} 0 ${body_height/2 + lidar_height/2}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${prefix}lidar">
      <visual>
        <origin xyz="${-rear_wheels_axis_offset} 0 ${body_height/2 + lidar_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${lidar_width} ${lidar_length} ${lidar_height}"/>
        </geometry>
        <material name="green"/>
      </visual>
    </link>

  </xacro:macro>

</robot>
