teleop_twist_joy_node:
  ros__parameters:
    axis_linear: # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular: # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 0.4

    enable_button: 6 # Left trigger button 6
    #enable_button: 0 # No enable needed, does not seem to work
    enable_turbo_button: 5 # Right trigger button
